### PR TITLE
Superseding readcontext

### PR DESCRIPTION
**Pull request by prdoyle**
Allow a `ReadContext` to be created that sees the latest bosk state rather than whatever is in any surrounding `ReadContext`.

This fairly simple change opens the door to using bosk to coordinate load-balanced work rather than just replicated work that happens on every node.

### CODE REVIEW

**Comment by prdoyle** [comment]
Hey @khchan. This is the first of a few PRs I'd like to merge, and then I'd like to do a release.

I'm not sure whether Vena has decided whether they still want me maintaining this library on the `venasolutions` org, or whether I should fork it and continue work on my own? I'm ok either way.

We could:

1. Get me permission to do bosk releases in the `venasolutions` org.
2. Have someone at Vena do a release.
3. I'll fork it and take over ownership outside the `venasolutions` org.

Any thoughts?

**Comment by prdoyle** [comment]
Hey @khchan. This is the first of a few PRs I'd like to merge, and then I'd like to do a release.

I'm not sure whether Vena has decided whether they still want me maintaining this library on the `venasolutions` org, or whether I should fork it and continue work on my own? I'm ok either way.

We could:

1. Get me permission to do bosk releases in the `venasolutions` org.
2. Have someone at Vena do a release.
3. I'll fork it and take over ownership outside the `venasolutions` org.

Any thoughts?

**Comment by khchan** [comment]
> Hey @khchan. This is the first of a few PRs I'd like to merge, and then I'd like to do a release.
> 
> I'm not sure whether Vena has decided whether they still want me maintaining this library on the `venasolutions` org, or whether I should fork it and continue work on my own? I'm ok either way.
> 
> We could:
> 
> 1. Get me permission to do bosk releases in the `venasolutions` org.
> 2. Have someone at Vena do a release.
> 3. I'll fork it and take over ownership outside the `venasolutions` org.
> 
> Any thoughts?

I'm asking around re the future of maintenance but I'm happy to assist with `2` in the meantime.

**Comment by prdoyle** [comment]
Ok thanks. I like working on bosk so I'm happy to do as much of it as Vena wants me to do.

**Comment by prdoyle** [comment]
The docs for creating a release are [here](https://docs.google.com/document/d/1c0Wq4ZpStNhZaE8gvFvpqIn_dsySGshKqFVHv2VJh9c/edit#heading=h.4yfyfldeefin), under the _Executing_ heading.

If you're going to do a release, you probably need to get your own Sonatype account and change the secrets as described in the _Secrets_ section [here](https://docs.google.com/document/d/1c0Wq4ZpStNhZaE8gvFvpqIn_dsySGshKqFVHv2VJh9c/edit#heading=h.fbfc87bpfejp). (The `GPG_PRIVATE_KEY` one can continue as is until November. It's the `OSSRH` ones that are specific to me.)

The learning curve is nontrivial. I'd be happy to Zoom and walk you through it the first time. There's a knack to it that takes some getting used to.

Also, it is possible to automate the Sonatype part of this, but I never got around to it.

**Comment by prdoyle** [comment]
I want to highlight again that the certificates used for publishing Bosk expire in November 2024. It's not a big deal, but we'd need to generate new certificates in order to keep publishing.

**Review by khchan — APPROVED** [review]

**Pull request merged**
