### PR TITLE
WIP - refactor submitReplacement to use Optional

### PR DESCRIPTION
**Pull request by gradycsjohnson**
Implementation of https://github.com/venasolutions/bosk/issues/22

Seems to be working so far. We need to carefully think about some of the edge cases though.

Thoughts?

### CODE REVIEW

**Comment by prdoyle** [comment]
Hmm, perhaps we can leave the existing methods as `default` methods on the `BoskDriver` interface for now? I suspect people are going to find it pretty annoying to have to use `Optional.of` every time they call `submitReplacement`.

**Comment by prdoyle** [comment]
Also... sorry about the merge conflicts. 😬

**Comment by gradycsjohnson** [comment]
Haha all good :)

**Comment by gradycsjohnson** [comment]
> Hmm, perhaps we can leave the existing methods as `default` methods on the `BoskDriver` interface for now? I suspect people are going to find it pretty annoying to have to use `Optional.of` every time they call `submitReplacement`.

You're right. I just wanted to figure out where the pitfalls would be and whether I could make the tests pass.

Turns out it was super easy, barely an inconvenience.

**Comment by prdoyle** [comment]
Hey @gradycsjohnson - are you in a position to move this forward any time soon? If you can't, I'd be happy to take it on.

**Comment by gradycsjohnson** [comment]
Yeah I should be able to get to it this weekend

**Comment by prdoyle** [comment]
Ok sounds good. No obligation! I don't mind doing it if you can't find the time.

**Comment by gradycsjohnson** [comment]
Superseded by https://github.com/venasolutions/bosk/pull/42

**Pull request closed without merging**
